@startuml

package "User collections" #DDDDDD {
  User <|-- Teller
  User <|-- CorporateUser
  User <|-- PrivateUser
}


package "Account collections" {
  Class Account {
    - branch_id
    - account_id
  }
  Class Transaction {
    - timestamp
    - account_id
    - amount
    - balance
  }

  Account "1"--"*" Transaction
}

package "General collections" {
  Class Settings 
}

package "Audit" {
  Class AuditLog
}

@enduml